apiVersion: v1
kind: Service
metadata:
  name: oficina-api-lb
  labels:
    app: oficina-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  selector:
    app: oficina-api